general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple instances
    before_sleep_cmd = loginctl lock-session    # lock before suspend
    after_sleep_cmd = hyprctl dispatch dpms on  # turn on display after wake
}

# Turn off the screen after 10 minutes (DPMS)
listener {
    timeout = 600                                
    on-timeout = hyprctl dispatch dpms off      
    on-resume = hyprctl dispatch dpms on         
}
