ipc = on
splash = false
preload = /home/sam/Pictures/liebe-black-clover-3840x2160-11223.jpg

wallpaper {
    monitor = DP-2
    path = /home/sam/Pictures/liebe-black-clover-3840x2160-11223.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-3
    path = /home/sam/Pictures/liebe-black-clover-3840x2160-11223.jpg
    fit_mode = cover
}
